#include "src/html_form.h"

const char form_html[] =
    "<!DOCTYPE html>\n"
    "<html>\n"
    "<head>\n"
    "  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no\">\n"
    "  <title>Clock Setup</title>\n"
    "  <style>\n"
    "    /* Base Reset & Typography */\n"
    "    * { box-sizing: border-box; }\n"
    "    body {\n"
    "      font-family: -apple-system, BlinkMacSystemFont, \"Segoe UI\", Roboto, Helvetica, Arial, sans-serif;\n"
    "      background-color: #f4f4f9;\n"
    "      color: #333;\n"
    "      margin: 0;\n"
    "      padding: 20px 15px;\n"
    "      display: flex;\n"
    "      justify-content: center;\n"
    "    }\n"
    "    \n"
    "    /* Form Container */\n"
    "    form {\n"
    "      width: 100%;\n"
    "      max-width: 400px;\n"
    "      background: #ffffff;\n"
    "      padding: 20px;\n"
    "      border-radius: 12px;\n"
    "      box-shadow: 0 4px 12px rgba(0,0,0,0.1);\n"
    "    }\n"
    "    \n"
    "    h2 {\n"
    "      margin-top: 0;\n"
    "      margin-bottom: 20px;\n"
    "      font-size: 22px;\n"
    "      text-align: center;\n"
    "      color: #111;\n"
    "    }\n"
    "    \n"
    "    /* Semantic Sectioning */\n"
    "    fieldset {\n"
    "      border: 1px solid #ddd;\n"
    "      border-radius: 8px;\n"
    "      padding: 15px;\n"
    "      margin: 0 0 20px 0;\n"
    "      background-color: #fafafa;\n"
    "    }\n"
    "    \n"
    "    legend {\n"
    "      font-weight: 600;\n"
    "      color: #555;\n"
    "      background: #ffffff;\n"
    "      padding: 0 8px;\n"
    "      border: 1px solid #ddd;\n"
    "      border-radius: 4px;\n"
    "      font-size: 14px;\n"
    "    }\n"
    "    \n"
    "    /* Standard Inputs, Selects & Labels */\n"
    "    label {\n"
    "      display: block;\n"
    "      font-size: 13px;\n"
    "      font-weight: 500;\n"
    "      margin-bottom: 6px;\n"
    "      color: #444;\n"
    "    }\n"
    "    \n"
    "    input[type=\"text\"], \n"
    "    input[type=\"password\"], \n"
    "    input[type=\"number\"], \n"
    "    select {\n"
    "      width: 100%;\n"
    "      padding: 10px 12px;\n"
    "      margin-bottom: 16px;\n"
    "      border: 1px solid #ccc;\n"
    "      border-radius: 6px;\n"
    "      font-size: 16px; /* 16px prevents iOS from auto-zooming on focus */\n"
    "      background: #fff;\n"
    "      transition: border-color 0.2s;\n"
    "      /* Appearance reset for consistent dropdown arrows on iOS/Android */\n"
    "      appearance: none; \n"
    "      -webkit-appearance: none;\n"
    "    }\n"
    "    \n"
    "    /* Clean up spacing for the last item in a box */\n"
    "    input:not([type=\"checkbox\"]):last-of-type,\n"
    "    select:last-of-type {\n"
    "      margin-bottom: 0;\n"
    "    }\n"
    "    \n"
    "    input:focus, select:focus {\n"
    "      outline: none;\n"
    "      border-color: #007bff;\n"
    "    }\n"
    "    \n"
    "    /* Checkbox & DST Row */\n"
    "    .checkbox-group {\n"
    "      display: flex;\n"
    "      align-items: center; /* Vertically center the box and text */\n"
    "      margin-top: 16px; \n"
    "    }\n"
    "    \n"
    "    .checkbox-group input[type=\"checkbox\"] {\n"
    "      width: 20px;\n"
    "      height: 20px;\n"
    "      margin: 0 10px 0 0; /* Space between box and label */\n"
    "      accent-color: #007bff; /* Colors the checkbox blue when ticked */\n"
    "    }\n"
    "    \n"
    "    .checkbox-group label {\n"
    "      margin-bottom: 0; /* Override the default label margin */\n"
    "      font-size: 14px;\n"
    "    }\n"
    "    \n"
    "    /* Submit Button */\n"
    "    button {\n"
    "      width: 100%;\n"
    "      padding: 14px;\n"
    "      background-color: #007bff;\n"
    "      color: white;\n"
    "      border: none;\n"
    "      border-radius: 8px;\n"
    "      font-size: 16px;\n"
    "      font-weight: 600;\n"
    "      cursor: pointer;\n"
    "      transition: background-color 0.2s;\n"
    "    }\n"
    "    \n"
    "    button:active {\n"
    "      background-color: #0056b3;\n"
    "    }\n"
    "  </style>\n"
    "</head>\n"
    "<body>\n"
    "  <form method=\"POST\" action=\"/clock-config\">\n"
    "    <h2>Clock Configuration</h2>\n"
    "\n"
    "    <fieldset>\n"
    "      <legend>Wi-Fi Network</legend>\n"
    "      \n"
    "      <label for=\"ssid\">Network Name (SSID)</label>\n"
    "      <input type=\"text\" id=\"ssid\" name=\"ssid\" required>\n"
    "\n"
    "      <label for=\"pwd\">Password</label>\n"
    "      <input type=\"password\" id=\"pwd\" name=\"pwd\" required>\n"
    "    </fieldset>\n"
    "\n"
    "    <fieldset>\n"
    "      <legend>Timezone</legend>\n"
    "      <label for=\"tz\">Timezone Offset</label>\n"
    "      <select id=\"tz\" name=\"tz\">\n"
    "        <option value=\"-12\">UTC -12:00 (Baker Island)</option>\n"
    "        <option value=\"-11\">UTC -11:00 (Samoa)</option>\n"
    "        <option value=\"-10\">UTC -10:00 (Hawaii)</option>\n"
    "        <option value=\"-9.5\">UTC -9:30 (Marquesas Islands)</option>\n"
    "        <option value=\"-9\">UTC -9:00 (Alaska)</option>\n"
    "        <option value=\"-8\">UTC -8:00 (Pacific Time)</option>\n"
    "        <option value=\"-7\">UTC -7:00 (Mountain Time)</option>\n"
    "        <option value=\"-6\">UTC -6:00 (Central Time)</option>\n"
    "        <option value=\"-5\">UTC -5:00 (Eastern Time)</option>\n"
    "        <option value=\"-4\">UTC -4:00 (Atlantic Time)</option>\n"
    "        <option value=\"-3.5\">UTC -3:30 (Newfoundland)</option>\n"
    "        <option value=\"-3\">UTC -3:00 (Argentina, Brazil)</option>\n"
    "        <option value=\"-2\">UTC -2:00 (South Georgia)</option>\n"
    "        <option value=\"-1\">UTC -1:00 (Azores, Cape Verde)</option>\n"
    "      \n"
    "        <option value=\"0\" selected>UTC +0:00 (GMT, Western Europe)</option>\n"
    "      \n"
    "        <option value=\"1\">UTC +1:00 (Central Europe, West Africa)</option>\n"
    "        <option value=\"2\">UTC +2:00 (Eastern Europe, Central Africa)</option>\n"
    "        <option value=\"3\">UTC +3:00 (Moscow, East Africa)</option>\n"
    "        <option value=\"3.5\">UTC +3:30 (Iran)</option>\n"
    "        <option value=\"4\">UTC +4:00 (Gulf Standard Time)</option>\n"
    "        <option value=\"4.5\">UTC +4:30 (Afghanistan)</option>\n"
    "        <option value=\"5\">UTC +5:00 (Pakistan)</option>\n"
    "        <option value=\"5.5\">UTC +5:30 (India Standard Time)</option>\n"
    "        <option value=\"5.75\">UTC +5:45 (Nepal)</option>\n"
    "        <option value=\"6\">UTC +6:00 (Bangladesh)</option>\n"
    "        <option value=\"6.5\">UTC +6:30 (Myanmar, Cocos Islands)</option>\n"
    "        <option value=\"7\">UTC +7:00 (Indochina, Western Indonesia)</option>\n"
    "        <option value=\"8\">UTC +8:00 (China, Western Australia)</option>\n"
    "        <option value=\"8.75\">UTC +8:45 (Eucla)</option>\n"
    "        <option value=\"9\">UTC +9:00 (Japan, Korea)</option>\n"
    "        <option value=\"9.5\">UTC +9:30 (Central Australia)</option>\n"
    "        <option value=\"10\">UTC +10:00 (Eastern Australia)</option>\n"
    "        <option value=\"10.5\">UTC +10:30 (Lord Howe Island)</option>\n"
    "        <option value=\"11\">UTC +11:00 (Solomon Islands)</option>\n"
    "        <option value=\"12\">UTC +12:00 (New Zealand, Fiji)</option>\n"
    "        <option value=\"12.75\">UTC +12:45 (Chatham Islands)</option>\n"
    "        <option value=\"13\">UTC +13:00 (Tonga, Samoa)</option>\n"
    "        <option value=\"14\">UTC +14:00 (Line Islands)</option>\n"
    "      </select>\n"
    "\n"
    "	  <div class=\"checkbox-group\">\n"
    "	    <input type=\"checkbox\" id=\"dst\" name=\"dst\" value=\"1\">\n"
    "        <label for=\"dst\">Use Daylight Saving Time</label>\n"
    "      </div>\n"
    "    </fieldset>\n"
    "\n"
    "    <fieldset>\n"
    "      <legend>Advanced Settings</legend>\n"
    "      \n"
    "      <label for=\"ntp\">NTP Time Server</label>\n"
    "      <input type=\"text\" id=\"ntp\" name=\"ntp\" value=\"pool.ntp.org\">\n"
    "\n"
    "      <label for=\"cto\">Connection Timeout (ms)</label>\n"
    "      <input type=\"number\" id=\"cto\" name=\"cto\" value=\"10000\">\n"
    "    </fieldset>\n"
    "\n"
    "    <button type=\"submit\">Save & Reboot</button>\n"
    "  </form>\n"
    "</body>\n"
    "</html>\n"
;
const unsigned int form_html_len = sizeof(form_html) - 1;

