#ifndef _STATUS_H
#define _STATUS_H

typedef enum
{
    STATUS_WIFI_OK = 0,
    STATUS_NTP_OK = 1,
    STATUS_WIFI_INIT = -1,
    STATUS_WIFI_TIMEOUT = -2,
    STATUS_WIFI_AUTH = -3,
    STATUS_WIFI_CONNECT = -4,
    STATUS_WIFI_ERROR = -5,
    STATUS_NTP_INIT = -6,
    STATUS_NTP_DNS = -7,
    STATUS_NTP_TIMEOUT = -8,
    STATUS_NTP_MEMORY = -9,
    STATUS_NTP_INVALID = -10,
    STATUS_WATCHDOG_RESET = -11,
    STATUS_NONE = 0xff,
} clock_status_t;

#endif // _STATUS_H
