name: Build and Test Project

on:
  push:
  pull_request:

jobs:
  build:
    name: Build (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Checkout project
        uses: actions/checkout@v4

      - name: Create config.cmake (non-Windows)
        if: matrix.os != 'windows-latest'
        run: |
          rm -f config.cmake
          echo 'set(WIFI_SSID "my-test-ssid")' >> config.cmake
          echo 'set(WIFI_PASSWORD "my-test-password")' >> config.cmake

      - name: Create config.cmake (Windows)
        if: matrix.os == 'windows-latest'
        run: |
          if (Test-Path config.cmake) { Remove-Item config.cmake }
          Add-Content config.cmake 'set(WIFI_SSID "my-test-ssid")'
          Add-Content config.cmake 'set(WIFI_PASSWORD "my-test-password")'
        shell: pwsh

      - name: Checkout Pico SDK
        uses: actions/checkout@v4
        with:
          repository: raspberrypi/pico-sdk
          path: pico-sdk
          ref: master
          submodules: recursive

      - name: Set environment vars
        run: |
          echo "PICO_SDK_PATH=pico-sdk" >> $GITHUB_ENV

      - name: Install dependencies (Ubuntu)
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake ninja-build lcov llvm gcc 
          sudo apt-get install -y gcc-arm-none-eabi libnewlib-arm-none-eabi

      # macOS runners have Homebrew pre-installed with CMake and Ninja
      - name: Install dependencies (macOS)
        if: matrix.os == 'macos-latest'
        run: |
          brew update
          brew install picotool llvm
          brew install --cask gcc-arm-embedded
          echo "$(brew --prefix gcc-arm-embedded)/bin" >> $GITHUB_PATH
          echo "$(brew --prefix llvm)/bin" >> $GITHUB_PATH

      # Windows runners have Homebrew pre-installed with CMake and Ninja
      - name: Install dependencies (Windows)
        if: matrix.os == 'windows-latest'
        run: choco install gcc-arm-embedded --version=10.3.1 -y
        shell: powershell

      - name: Configure CMake
        run: cmake -DCMAKE_BUILD_TYPE=Debug -DPICO_SDK_PATH=pico-sdk -B build -G Ninja

      - name: Build Pico target
        run: |
          ninja -v -C build generate_fonts
          ninja -v -C build picow_day_clock

      - name: Build native target and run tests (macOS)
        if: matrix.os == 'macos-latest'
        run: |
          ninja -v -C build test_picow_day_clock
          cmake --build build --target run_tests
          cmake --build build --target coverage_llvm

      - name: Build native target and run tests (Ubuntu)
        if: matrix.os == 'ubuntu-latest'
        run: |
          ninja -v -C build test_picow_day_clock
          cmake --build build --target run_tests
          cmake --build build --target coverage_llvm

      - name: Build native target and run tests (Windows)
        if: matrix.os == 'windows-latest'
        run: |
          ninja -v -C build test_picow_day_clock
          cmake --build build --target run_tests --verbose
